{
  "name": "vuenice-admin-app",
  "private": true,
  "version": "0.0.0",
  "description": "Scaffolded VueNice admin SPA. Edit freely.",
  "type": "module",
  "scripts": {
    "typecheck": "vue-tsc --noEmit"
  },
  "dependencies": {
    "vue": "^3.4.0",
    "vue-router": "^4.3.0",
    "pinia": "^2.1.7",
    "axios": "^1.6.0",
    "vue-nice-validate": "^3.2.5",
    "vue-multi-step-form": "^0.1.0",

    "vue-nice-input": "github:vuenice/input",
    "vue-nice-button": "github:vuenice/button",
    "vue-nice-alert": "github:vuenice/vue-nice-alert",
    "vue-nice-modal": "github:vuenice/vue-nice-modal",
    "vue-nice-tabs": "github:vuenice/vue-nice-tabs",
    "vue-nice-table": "github:vuenice/vue-nice-table",
    "vue-nice-table-skeleton": "github:vuenice/vue-nice-table-skeleton",
    "vue-nice-menu": "github:vuenice/vue-nice-menu",
    "vue-nice-sidebar": "github:vuenice/vue-nice-sidebar",
    "vue-nice-sidebar-menu": "github:vuenice/vue-nice-sidebar-menu",
    "vue-nice-header": "github:vuenice/vue-nice-header",
    "vue-nice-breadcrumb": "github:vuenice/vue-nice-breadcrumb",
    "vue-nice-pagination": "github:vuenice/vue-nice-pagination",
    "vue-nice-loader": "github:vuenice/vue-nice-loader",
    "vue-nice-icon": "github:vuenice/vue-nice-icon",
    "vue-nice-icon-button": "github:vuenice/vue-nice-icon-button",
    "vue-nice-progress": "github:vuenice/vue-nice-progress",
    "vue-nice-progress-bar": "github:vuenice/vue-nice-progress-bar",
    "vue-nice-progress-circle": "github:vuenice/vue-nice-progress-circle",
    "vue-nice-checkbox": "github:vuenice/vue-nice-checkbox",
    "vue-nice-checkbox-button": "github:vuenice/vue-nice-checkbox-button",
    "vue-nice-radio": "github:vuenice/vue-nice-radio",
    "vue-nice-switch": "github:vuenice/vue-nice-switch",
    "vue-nice-popover": "github:vuenice/vue-nice-popover",
    "vue-nice-tag": "github:vuenice/vue-nice-tag",
    "vue-nice-multi-tag-input": "github:vuenice/vue-nice-multi-tag-input",
    "vue-nice-autocomplete": "github:vuenice/vue-nice-autocomplete",
    "vue-nice-listbox": "github:vuenice/vue-nice-listbox",
    "vue-nice-slider": "github:vuenice/vue-nice-slider",
    "vue-nice-avatar": "github:vuenice/vue-nice-avatar",
    "vue-nice-account-dropdown": "github:vuenice/vue-nice-account-dropdown",
    "vue-nice-action-dropdown": "github:vuenice/vue-nice-action-dropdown",
    "vue-nice-action-button-group": "github:vuenice/vue-nice-action-button-group",
    "vue-nice-dialog": "github:vuenice/vue-nice-dialog",
    "vue-nice-confirmation-modal": "github:vuenice/vue-nice-confirmation-modal",
    "vue-nice-split-modal": "github:vuenice/vue-nice-split-modal",
    "vue-nice-form-section": "github:vuenice/vue-nice-form-section",
    "vue-nice-accordion": "github:vuenice/vue-nice-accordion",
    "vue-nice-copy-button": "github:vuenice/vue-nice-copy-button",
    "vue-nice-debug": "github:vuenice/vue-nice-debug",
    "vue-nice-logo-upload": "github:vuenice/vue-nice-logo-upload"
  },
  "devDependencies": {
    "vue-tsc": "^2.0.6",
    "@types/node": "^20.11.0",
    "typescript": "^5.4.0"
  },
  "_notes": "Most VueNice components are GitHub-only as of writing. If a particular GitHub install fails (e.g. the repo has no dist build), comment out that entry — the scaffold ships local fallback components for the layout-critical pieces (sidebar menu, header, button, input, alert) so the SPA still boots."
}
